language: node_js
node_js:
  - 6.11.5
script: node_modules/karma/bin/karma start --single-run --single-run --browsers PhantomJS karma.conf.js
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
